### ISSUE TITLE
File zip dianggap ada virus sehingga tidak bisa dio download

### ISSUE THREAD

**Issue by jodyaryono** [veritrans/SNAP-Prestashop#12]
![image](https://user-images.githubusercontent.com/6079404/47268315-8a215700-d579-11e8-86b4-a7a27973c43f.png)

Tidak bisa di zip menjadi veritranspay.zip karena dianggap ada virus , mohon bantu untuk perbaikannya
thanks

**Comment by rizdaprasetya** [comment]
Hi @jodyaryono 
File module ini sudah dipastikan bebas virus, silahkan hasil analisa anti-virus berikut:
https://www.virustotal.com/#/file/ece6d1f23e5dbfa35f389976a83e121d388d28c87b762527c5eab4ab987ad9d2/detection
![screen shot 2018-10-22 at 11 52 43 am](https://user-images.githubusercontent.com/13027142/47278189-1fabfd80-d5f1-11e8-8a10-e0e1fe77e965.png)

Tidak ada orang lain yang mengalami masalah tersebut.
Menurut saya:

- WinRar atau Windows anda sudah false detection, silahkan gunakan software extraction yang lain.
- atau memang PC anda yang sudah terinfeksi virus, sehingga file yang di download otomatis terinfect virus. Silahkan dicek kembali PCnya.

Tidak akan ada action dari kami untuk perbaikan atau sejenisnya karena issue bukan dari sisi kami.
Terima kasih.

**Comment by rizdaprasetya** [comment]
Hi @jodyaryono 

File module ini sudah dipastikan bebas virus, silahkan cek hasil analisa antivirus berikut:
https://www.virustotal.com/#/file/ece6d1f23e5dbfa35f389976a83e121d388d28c87b762527c5eab4ab987ad9d2/detection
![screen shot 2018-10-22 at 11 52 43 am](https://user-images.githubusercontent.com/13027142/47278308-10797f80-d5f2-11e8-8251-42c4a6a93b33.png)

Tidak ada orang lain atau pengguna lain yang mengalami issue tersebut.

Kemungkinan:
- Software extraction / Windows yang anda gunakan melakukan false detection, silahkan gunakan software lain
- PC anda terinfeksi virus, jadi semua file yg didownload otomatis terinfeksi virus juga. Silahkan cek PCnya

Dari kami tidak akan ada action perbaikan atau sejenisnya karena memang issuenya bukan dari kami.
Terima kasih

**Comment by rizdaprasetya** [comment]
Hi @jodyaryono 

File module ini sudah dipastikan bebas virus, silahkan cek hasil analisa antivirus berikut:
https://www.virustotal.com/#/file/ece6d1f23e5dbfa35f389976a83e121d388d28c87b762527c5eab4ab987ad9d2/detection
![screen shot 2018-10-22 at 11 52 43 am](https://user-images.githubusercontent.com/13027142/47278308-10797f80-d5f2-11e8-8251-42c4a6a93b33.png)

Tidak ada orang lain atau pengguna lain yang mengalami issue tersebut.

Kemungkinan:
- Software extraction / Windows yang anda gunakan melakukan false detection, silahkan gunakan software lain
- PC anda terinfeksi virus, jadi semua file yg didownload otomatis terinfeksi virus juga. Silahkan cek PCnya

Dari kami tidak akan ada action perbaikan atau sejenisnya karena memang issuenya bukan dari kami.
Terima kasih
