### ISSUE TITLE
not installing on latest 1.7

### ISSUE THREAD

**Issue by pks891618** [veritrans/SNAP-Prestashop#26]
not working Please check the screenshot 

http://i.imgur.com/SIFzmWj.png

Prestashop version :1.7.8.5

**Comment by Andrenzo17** [comment]
Hi @pks891618 

I have tested using Prestashop version :1.7.8.5 and the Midtrans Prestashop Payment Gateway Module can work.
Please make sure, you properly following the guide especially the part where need to unzip, rename, re-zip. 
Also, you can the see [prestashop plugin-installation and configuration in here](https://docs.midtrans.com/en/snap/with-plugins?id=prestashop-plugin-installation-and-configuration)

Thank you
