### ISSUE TITLE
PrestaShop 1.7 Support?

### ISSUE THREAD

**Issue by blazeu** [veritrans/SNAP-Prestashop#3]
Does this package supports PrestaShop 1.7 ?

**Comment by rizdaprasetya** [comment]
Hi @blazeu 
PrestaShop v1.7 is supported, but for now it's on another branch of this repo:
https://github.com/veritrans/SNAP-Prestashop/tree/prestashop1.7

Feel free to use and report if you find any issue. Thanks.
